language: python
python:
    - "2.7"
before_script:
  - wget "http://gyamp.com/hiroshi/google_appengine_zip" -nv
  - unzip -q google_appengine_zip
  - sudo ln -s `pwd`/google_appengine/dev_appserver.py /usr/local/bin/dev_appserver.py
script: ant test
